baseURL = "https://xuwan123-liang.github.io/"
languageCode = "zh-cn"
title = "徐皖亮 | AI & Finance"
theme = "hugo-theme-stack"

[outputs]
    home = ["HTML", "RSS", "JSON"]

[params]
    mainSections = ["post"]
    featuredImageField = "image"

    [params.sidebar]
        avatar = "images/avatar.jpg"
        title = "徐皖亮"
        subtitle = "AI & Finance | Tech Blogger"

    [params.colorScheme]
        toggle = true
        default = "auto"

[[menu.main]]
    identifier = "about"
    name = "关于我"
    url = "/about/"
    weight = 10

[[menu.main]]
    identifier = "post"
    name = "项目集"
    url = "/post/"
    weight = 20